name: gui_final
description: A Flutter project for managing customers.

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.2.8+4
  path: ^1.8.3
  shared_preferences: ^2.2.0
  flutter_secure_storage: ^7.0.0
  flutter_localizations:
    sdk: flutter
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.4
  json_serializable: ^6.6.2

flutter:
  uses-material-design: true
