name: airplane_management
description: A Flutter application for managing airplanes.
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0" # Ensure this matches your Dart SDK version

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  floor: ^1.4.0
  sqflite: ^2.0.0+4
  flutter_secure_storage: ^7.0.0 # For encrypted storage
  shared_preferences: ^2.0.15 # For shared preferences
  provider: ^6.0.5 # For state management, if needed
  flutter_localizations: # For localization support
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.2 # For code generation for Floor
  floor_generator: ^1.4.0 # Floor generator for code generation

flutter:
  uses-material-design: true

  assets:
    - images/airplane.jpg
    - images/airplane1.jpg

