name: final_project
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  floor: ^1.4.0
  path: ^1.8.0
  path_provider: ^2.0.11
  shared_preferences: ^2.0.6
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  encrypt: ^5.0.0
  flutter_secure_storage: ^5.0.2

dev_dependencies:
  floor_generator: ^1.4.0
  build_runner: ^2.1.2
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - images/airplane.jpg
    - images/airplane1.jpg
