name: cst2335_summer24
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  encrypted_shared_preferences: ^3.0.1
  url_launcher: ^6.3.0
  sqflite: ^2.0.0+4
  sembast: ^3.0.0
  sembast_web: ^2.2.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0
  flutter_secure_storage: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.2
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:

    - images/background.jpg
