name: final_project_android
description: A Flutter project for managing customers.

environment:
  sdk: '>=2.17.0 <4.0.0' # Ensure compatibility with null safety

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  sqflite: ^2.2.8+4 # Ensure it's a null-safe version
  path: ^1.8.3
  shared_preferences: ^2.2.0 # Updated to the latest version
  floor: ^1.1.0
  floor_generator: ^1.1.0
  sembast: ^3.1.1
  sembast_web: ^2.4.0+2 # Use the latest version that is compatible
  flutter_secure_storage: ^6.0.0 # Secure storage for credentials
  json_annotation: ^4.8.1 # Latest compatible version

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.4 # Updated to the latest version
  json_serializable: ^6.6.2 # Updated to the latest version
